[
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Ramon Ferreira*",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "17h00",
      "Ultima entrevista": "10/05",
      "Último teste": "08/07",
      "Destaque H1": 35,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Almir Mendes*",
      "Time": "CRM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "31/08",
      "Destaque H1": 27,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "André Junior*",
      "Time": "Tech Lead",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "17/02/2021",
      "Último teste": "26/07/2021",
      "Destaque H1": 21,
      "": "Full-stack",
      "__1": 11
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Daniel Vinciguerra*",
      "Time": "Tech Lead/RDSM",
      "Front/Back": "Full-Stack/Front",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "31/08",
      "Destaque H1": 17,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Daiane Santos",
      "Time": "RDSM",
      "Front/Back": "Full-Stack/Front",
      "Dia da semana": "Quarta",
      "Horário": "9h00",
      "Ultima entrevista": "10/05",
      "Último teste": "25/05",
      "Destaque H1": 15,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Rogério Angeliski",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quinta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "07/06",
      "Destaque H1": 13,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Tarciso Scariot",
      "Time": "Tech Lead/RMS",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quinta",
      "Horário": "9h00",
      "Ultima entrevista": "22/02",
      "Último teste": "11/06",
      "Destaque H1": 10,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Henrich Moraes*",
      "Time": "Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "15/07",
      "Destaque H1": 9,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Hudolf Hess*",
      "Time": "Tech Lead/RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "11/05",
      "Destaque H1": 9,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Paulo Casaretto*",
      "Time": "Tech Lead / Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "06/05/2021",
      "Último teste": "06/05/2021",
      "Destaque H1": 9,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Edmilton",
      "Time": "Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "17h00",
      "Ultima entrevista": "05/04",
      "Último teste": "12/07",
      "Destaque H1": 8,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Guilherme Fonseca",
      "Time": "Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "04/06",
      "Destaque H1": 8,
      "": "Devas",
      "__1": 2
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Jean Toledo",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "25/05",
      "Destaque H1": 8,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Francis",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "29/01",
      "Último teste": "20/07",
      "Destaque H1": 7,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Gabriel Augusto Barbosa",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "01/06",
      "Destaque H1": 6,
      "": "Front",
      "__1": 2
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Tiago Cussiol",
      "Time": "CRM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "20/07",
      "Destaque H1": 6,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Bernardo Brunning",
      "Time": "Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "08/07",
      "Destaque H1": 3,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Nando Sousa",
      "Time": "Tech Lead / Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quinta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "20/05",
      "Destaque H1": 3,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Douglas Schuelter",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "12/07",
      "Destaque H1": 2,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Fabio Ariati",
      "Time": "Platform",
      "Front/Back": "Full-stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "20/07",
      "Destaque H1": 2,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Rodrigo Campos",
      "Time": "CRM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "17/05",
      "Destaque H1": 2,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Jean Matheus",
      "Time": "Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "31/05",
      "Destaque H1": 1,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Yuri Lopes",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "04/06",
      "Destaque H1": 1,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Anderson Oliveira",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Antonio José Alves",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "10/02",
      "Último teste": "26/04",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Cesar Henrique Selonke",
      "Time": "Tech Lead/Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "10/02",
      "Último teste": "26/04",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Henrique Holanda",
      "Time": "Intl",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quarta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Joacir Oliveira Santos Jr.",
      "Time": "CRM",
      "Front/Back": "Full-stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "João Gustavo de Paula",
      "Time": "RMS",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Ramires Oliveira",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quinta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Sidney dos Santos Souza",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quinta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Tiago Pereira",
      "Time": "RDSM",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Quinta",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Wagner Andrade",
      "Time": "PLG",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "",
      "Status": "",
      "Nome": "",
      "Time": "",
      "Front/Back": "",
      "Dia da semana": "",
      "Horário": "",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "Front",
      "Status": "",
      "Nome": "",
      "Time": "",
      "Front/Back": "",
      "Dia da semana": "",
      "Horário": "",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Bruno Nardini*",
      "Time": "RDSM",
      "Front/Back": "Front",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "12/04",
      "Último teste": "06/08",
      "Destaque H1": 17,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "João Paulo Barbosa",
      "Time": "RDSM",
      "Front/Back": "Front",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "24/08",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Jonas Antonelli",
      "Time": "CRM",
      "Front/Back": "Front",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "10/05/2021",
      "Último teste": "06/08",
      "Destaque H1": 4,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Rafael Camargo",
      "Time": "CRM",
      "Front/Back": "Front",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "12/04",
      "Último teste": "20/07",
      "Destaque H1": 12,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Augusto Sandim",
      "Time": "CRM",
      "Front/Back": "Front",
      "Dia da semana": "Terça",
      "Horário": "9h00",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Kaio Silva",
      "Time": "RDSM",
      "Front/Back": "Front",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "12/02",
      "Último teste": "",
      "Destaque H1": 2,
      "": "",
      "__1": ""
    },
    {
      "Invites": "",
      "Status": "",
      "Nome": "",
      "Time": "",
      "Front/Back": "",
      "Dia da semana": "",
      "Horário": "",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "Girls",
      "Status": "",
      "Nome": "",
      "Time": "",
      "Front/Back": "",
      "Dia da semana": "",
      "Horário": "",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Camila Pauli",
      "Time": "RDSM/Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "Terça",
      "Horário": "17h00",
      "Ultima entrevista": "",
      "Último teste": "12/04",
      "Destaque H1": 8,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Mentor",
      "Nome": "Marcela Sisliani",
      "Time": "Tech Lead/Platform",
      "Front/Back": "Full-Stack",
      "Dia da semana": "-",
      "Horário": "-",
      "Ultima entrevista": "10/02",
      "Último teste": "26/04",
      "Destaque H1": 12,
      "": "",
      "__1": ""
    },
    {
      "Invites": "FALSE",
      "Status": "Lead",
      "Nome": "Silvana Lima",
      "Time": "CRM",
      "Front/Back": "Front",
      "Dia da semana": "",
      "Horário": "",
      "Ultima entrevista": "",
      "Último teste": "",
      "Destaque H1": "",
      "": "",
      "__1": ""
    },
  ]
  
  